name: Feature Request
description: Propose a new feature for BriefBot
title: "[Feature]: "
labels: ["feature", "needs-planning"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a new feature! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature do you want to add?
      placeholder: "As a user, I want to..."
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the user story for this feature
      placeholder: |
        As a [type of user],
        I want to [action],
        So that [benefit].
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What must be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any issues this depends on, or "None"
      placeholder: |
        Blocked by: #123, #124
        Or: None
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: Which area of the codebase does this affect?
      options:
        - frontend
        - backend
        - database
        - ai-ml
        - infra
        - auth
        - multiple
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical considerations or implementation hints
      placeholder: "Optional: API changes, database schema, etc."
    validations:
      required: false
